// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ObiaNzk/LTK-test-manu/internal (interfaces: ServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks github.com/ObiaNzk/LTK-test-manu/internal ServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// HelloWorld mocks base method.
func (m *MockServiceInterface) HelloWorld() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HelloWorld")
	ret0, _ := ret[0].(string)
	return ret0
}

// HelloWorld indicates an expected call of HelloWorld.
func (mr *MockServiceInterfaceMockRecorder) HelloWorld() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HelloWorld", reflect.TypeOf((*MockServiceInterface)(nil).HelloWorld))
}
