// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ObiaNzk/LTK-test-manu/cmd/api/handlers (interfaces: eventsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_events_service.go -package=mocks github.com/ObiaNzk/LTK-test-manu/cmd/api/handlers eventsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	internal "github.com/ObiaNzk/LTK-test-manu/internal"
	gomock "go.uber.org/mock/gomock"
)

// MockeventsService is a mock of eventsService interface.
type MockeventsService struct {
	ctrl     *gomock.Controller
	recorder *MockeventsServiceMockRecorder
	isgomock struct{}
}

// MockeventsServiceMockRecorder is the mock recorder for MockeventsService.
type MockeventsServiceMockRecorder struct {
	mock *MockeventsService
}

// NewMockeventsService creates a new mock instance.
func NewMockeventsService(ctrl *gomock.Controller) *MockeventsService {
	mock := &MockeventsService{ctrl: ctrl}
	mock.recorder = &MockeventsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventsService) EXPECT() *MockeventsServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockeventsService) CreateEvent(ctx context.Context, event internal.CreateEventRequest) (internal.CreateEventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(internal.CreateEventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockeventsServiceMockRecorder) CreateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockeventsService)(nil).CreateEvent), ctx, event)
}

// GetEventByID mocks base method.
func (m *MockeventsService) GetEventByID(ctx context.Context, id string) (internal.CreateEventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByID", ctx, id)
	ret0, _ := ret[0].(internal.CreateEventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByID indicates an expected call of GetEventByID.
func (mr *MockeventsServiceMockRecorder) GetEventByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByID", reflect.TypeOf((*MockeventsService)(nil).GetEventByID), ctx, id)
}
